#+STARTUP: showall
#+TITLE: Emacs tips

* Commands
** Case  
- M-l
Convert following word to lower case (downcase-word).

- M-u
Convert following word to upper case (upcase-word). e.g. create abc -> CREATE abc

- M-c
Capitalize the following word (capitalize-word). e.g. create abc -> Create abc

- C-x C-l
Convert region to lower case (downcase-region).

- C-x C-u
Convert region to upper case (upcase-region).


** Query replace
- M-% string RET newstring RET
Replace some occurrences of string with newstring.

C-M-% regexp RET newstring RET
Replace some matches for regexp with newstring.

** Rectangles
- C-x r ?

** Insert sth to the begining of each line in a selected rectangle
   M-x string-insert-rectangle

* Modes
** org-mode
[[file:org_mode.org][Notes for org-mode]]

** Python IDE
   - jedi and elpy, Emacs can be a powerful Python IDE.
   - EIN, you can run Jupyter Notebooks within Emacs.
     1. C-x C-o to open a .ipynb file, or
     2. M-x ein:run launches a new Jupyter Process from Emacs, or
     3. M-x ein:login to a running Jupyter Server.
